//gotQuotes.js
const gotQuotes = [
  { id: 1, quote: "Der Winter naht.", character: "Ned Stark", house: "Stark", epic: true },
  { id: 2, quote: "Der König im Norden!", character: "Jon Snow", house: "Stark", epic: true },
  { id: 3, quote: "Die Pflicht ist oft schwerer als die Liebe.", character: "Sansa Stark", house: "Stark", epic: false },
  { id: 4, quote: "Ein Wolf allein ist schwach, doch das Rudel überlebt.", character: "Arya Stark", house: "Stark", epic: true },
  { id: 5, quote: "Manchmal ist das Herz stärker als die Vernunft.", character: "Catelyn Stark", house: "Stark", epic: false },
  { id: 6, quote: "Ein Löwe kümmert sich nicht um die Meinung von Schafen.", character: "Tywin Lannister", house: "Lannister", epic: true },
  { id: 7, quote: "Ein Lannister begleicht stets seine Schuld.", character: "Tyrion Lannister", house: "Lannister", epic: true },
  { id: 8, quote: "Ich trinke und ich weiß Dinge.", character: "Tyrion Lannister", house: "Lannister", epic: true },
  { id: 9, quote: "Wenn du spielst, um zu gewinnen, musst du bereit sein, alles zu opfern.", character: "Cersei Lannister", house: "Lannister", epic: true },
  { id: 10, quote: "Rache ist ein Gericht, das am besten kalt serviert wird.", character: "Cersei Lannister", house: "Lannister", epic: false },
  { id: 11, quote: "Dracarys!", character: "Daenerys Targaryen", house: "Targaryen", epic: true },
  { id: 12, quote: "Ich bin das Blut des Drachen.", character: "Daenerys Targaryen", house: "Targaryen", epic: true },
  { id: 13, quote: "Ein Drache ist kein Sklave.", character: "Daenerys Targaryen", house: "Targaryen", epic: true },
  { id: 14, quote: "Ich werde die Ketten sprengen.", character: "Daenerys Targaryen", house: "Targaryen", epic: true },
  { id: 15, quote: "Der Drache ist tot.", character: "Daenerys Targaryen", house: "Targaryen", epic: false },
  { id: 16, quote: "Ich bin der Sturm.", character: "Robert Baratheon", house: "Baratheon", epic: true },
  { id: 17, quote: "Die Nacht ist dunkel und voller Schrecken.", character: "Melisandre", house: "Asshai", epic: true },
  { id: 18, quote: "Der wahre König ist der, der den Thron nimmt.", character: "Stannis Baratheon", house: "Baratheon", epic: true },
  { id: 19, quote: "Ich werde König oder gar nichts.", character: "Renly Baratheon", house: "Baratheon", epic: false },
  { id: 20, quote: "Ein König muss kämpfen, nicht nur befehlen.", character: "Stannis Baratheon", house: "Baratheon", epic: false },
  { id: 21, quote: "Was tot ist, kann niemals sterben.", character: "Balon Greyjoy", house: "Greyjoy", epic: true },
  { id: 22, quote: "Ich bin der Kraken.", character: "Euron Greyjoy", house: "Greyjoy", epic: true },
  { id: 23, quote: "Wir säen nicht.", character: "Yara Greyjoy", house: "Greyjoy", epic: true },
  { id: 24, quote: "Das Meer gehört uns.", character: "Theon Greyjoy", house: "Greyjoy", epic: false },
  { id: 25, quote: "Der Kraken erhebt sich.", character: "Euron Greyjoy", house: "Greyjoy", epic: false },
  { id: 26, quote: "Ungebeugt, Ungezähmt, Ungebrochen.", character: "Oberyn Martell", house: "Martell", epic: true },
  { id: 27, quote: "Ich wähle Gewalt.", character: "Ellaria Sand", house: "Martell", epic: true },
  { id: 28, quote: "Ich bin die Viper.", character: "Oberyn Martell", house: "Martell", epic: true },
  { id: 29, quote: "Die Sonne wird immer wieder aufgehen.", character: "Doran Martell", house: "Martell", epic: false },
  { id: 30, quote: "Sand wird den Sturm überstehen.", character: "Nymeria Sand", house: "Martell", epic: false },
  { id: 31, quote: "Wachsen und Blühen.", character: "Margaery Tyrell", house: "Tyrell", epic: true },
  { id: 32, quote: "Ich habe keine Angst zu sterben.", character: "Olenna Tyrell", house: "Tyrell", epic: true },
  { id: 33, quote: "Sag Cersei, ich war es.", character: "Olenna Tyrell", house: "Tyrell", epic: true },
  { id: 34, quote: "Eine Rose hat auch Dornen.", character: "Margaery Tyrell", house: "Tyrell", epic: false },
  { id: 35, quote: "Die Stärke wächst aus den Wurzeln.", character: "Loras Tyrell", house: "Tyrell", epic: false },
  { id: 36, quote: "Hoch wie die Ehre.", character: "Jon Arryn", house: "Arryn", epic: true },
  { id: 37, quote: "Die Eyrie ist uneinnehmbar.", character: "Lysa Arryn", house: "Arryn", epic: false },
  { id: 38, quote: "Ehre vor Ruhm.", character: "Robin Arryn", house: "Arryn", epic: false },
  { id: 39, quote: "Familie, Pflicht, Ehre.", character: "Catelyn Tully", house: "Tully", epic: true },
  { id: 40, quote: "Der Fisch schwimmt gegen den Strom.", character: "Edmure Tully", house: "Tully", epic: false },
  { id: 41, quote: "Ich bin der Bluthund.", character: "Sandor Clegane", house: "Clegane", epic: false },
  { id: 42, quote: "Bringt mir Wein.", character: "Gregor Clegane", house: "Clegane", epic: false },
  { id: 43, quote: "Ein Mann hat keinen Namen.", character: "Jaqen H’ghar", house: "Faceless Men", epic: true },
  { id: 44, quote: "Valar Morghulis.", character: "Jaqen H’ghar", house: "Faceless Men", epic: true },
  { id: 45, quote: "Valar Dohaeris.", character: "Jaqen H’ghar", house: "Faceless Men", epic: true },
  { id: 46, quote: "Chaos ist eine Leiter.", character: "Petyr Baelish", house: "Baelish", epic: true },
  { id: 47, quote: "Alles, was wir tun, ist in Bewegung.", character: "Varys", house: "None", epic: false },
  { id: 48, quote: "Das Reich – das ist eine Illusion.", character: "Varys", house: "None", epic: true },
  { id: 49, quote: "Wissen ist Macht.", character: "Petyr Baelish", house: "Baelish", epic: false },
  { id: 50, quote: "Die Wahrheit ist grausam.", character: "Varys", house: "None", epic: false },
  { id: 51, quote: "Das Schwert in der Dunkelheit.", character: "Nachtwache", house: "None", epic: true },
  { id: 52, quote: "Ich schwöre einen Eid.", character: "Jon Snow", house: "Stark", epic: true },
  { id: 53, quote: "Die Nacht gehört dem Wolf.", character: "Ghost", house: "Stark", epic: false },
  { id: 54, quote: "Der Norden vergisst nicht.", character: "Robb Stark", house: "Stark", epic: true },
  { id: 55, quote: "Das Lied von Eis und Feuer.", character: "Samwell Tarly", house: "Tarly", epic: true },
  { id: 56, quote: "Die alten Götter wachen.", character: "Bran Stark", house: "Stark", epic: true },
  { id: 57, quote: "Ich bin kein Held.", character: "Theon Greyjoy", house: "Greyjoy", epic: false },
  { id: 58, quote: "Der Tod ist schneller als das Schwert.", character: "Brienne von Tarth", house: "Tarth", epic: false },
  { id: 59, quote: "Ein Ritter schwört immer.", character: "Brienne von Tarth", house: "Tarth", epic: true },
  { id: 60, quote: "Die Ketten sind schwer, doch sie brechen.", character: "Missandei", house: "Targaryen", epic: false },
  { id: 61, quote: "Ich werde meine Kinder beschützen.", character: "Cersei Lannister", house: "Lannister", epic: true },
  { id: 62, quote: "Die Winde des Winters kommen.", character: "Stark Motto", house: "Stark", epic: true },
  { id: 63, quote: "Die Saat ist stark.", character: "Stannis Baratheon", house: "Baratheon", epic: false },
  { id: 64, quote: "Das Spiel der Throne kennt keine Gnade.", character: "Varys", house: "None", epic: true },
  { id: 65, quote: "Nur Feuer kann Finsternis besiegen.", character: "Melisandre", house: "Asshai", epic: true },
  { id: 66, quote: "Ein König ohne Krone ist nur ein Mann.", character: "Davos Seaworth", house: "None", epic: false },
  { id: 67, quote: "Manchmal musst du deine Familie verraten, um sie zu retten.", character: "Tyrion Lannister", house: "Lannister", epic: false },
  { id: 68, quote: "Das Leben ist keine Geschichte, Mädchen.", character: "Sandor Clegane", house: "Clegane", epic: false },
  { id: 69, quote: "Freiheit ist süßer als Blut.", character: "Daenerys Targaryen", house: "Targaryen", epic: true },
  { id: 70, quote: "Die Kälte kennt keine Gnade.", character: "Weißer Wanderer", house: "None", epic: true },
  { id: 71, quote: "Ich bin der Nachtkönig.", character: "Nachtkönig", house: "None", epic: true },
  { id: 72, quote: "Die Mauer hält.", character: "Nachtwache", house: "None", epic: true },
  { id: 73, quote: "Das Feuer wird sie reinigen.", character: "Melisandre", house: "Asshai", epic: true },
  { id: 74, quote: "Ein Schwert braucht einen starken Arm.", character: "Bronn", house: "None", epic: false },
  { id: 75, quote: "Gold kauft Loyalität.", character: "Petyr Baelish", house: "Baelish", epic: false },
  { id: 76, quote: "Die Welt ist voller Lügen.", character: "Varys", house: "None", epic: false },
  { id: 77, quote: "Jeder Mensch ist sterblich.", character: "Faceless Men", house: "Faceless Men", epic: true },
  { id: 78, quote: "Stärke ist alles.", character: "Gregor Clegane", house: "Clegane", epic: false },
  { id: 79, quote: "Ein König ohne Volk ist kein König.", character: "Robert Baratheon", house: "Baratheon", epic: false },
  { id: 80, quote: "Die Geschichten werden weiterleben.", character: "Samwell Tarly", house: "Tarly", epic: true }
];


export default gotQuotes;